version: "3"

services:
  market_db:
    container_name: market_db
    image: postgres
    env_file:
      - ./.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - marketnet
    restart: unless-stopped
  market_backend:
    container_name: market_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - ./.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Host=market_db;Port=5432;Database=marketplace;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_URLS=http://*:5000
    networks:
      - marketnet
    depends_on:
      - "market_db"
  # market_escrow:
  #   container_name: market_escrow
  #   build:
  #     context: ./backend
  #     dockerfile: ./Dockerfile.escrow
  #   ports:
  #     - "5002:5002"
  #   env_file:
  #     - ./.env
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionString=Host=market_db;Port=5432;Database=marketplace;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  #     - ASPNETCORE_URLS=http://*:5002
  #   networks:
  #     - marketnet
  #   depends_on:
  #     - "market_db"
  
  mint_backend:
    container_name: mint_backend
    build:
      context: ./mint_backend
      dockerfile: ./Dockerfile
    ports:
      - "3003:3003"
    networks:
      - marketnet
    volumes:
      - ./images:/usr/src/app/images
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - marketnet
    depends_on:
      - "market_backend"

networks:
  marketnet:
    driver: bridge

volumes:
  postgres: