version: "3"

x-marketplace: &marketplace-backend
  image: docker.io/uniquenetwork/marketplace-backend
  restart: unless-stopped
  environment:
    ESCROW_SEED: ${ESCROW_SEED}
    AUCTION_SEED: ${AUCTION_SEED}
    CONTRACT_ETH_OWNER_SEED: ${CONTRACT_ETH_OWNER_SEED}
    CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
    UNIQUE_COLLECTION_IDS: ${UNIQUE_COLLECTION_IDS}
    POSTGRES_URL: ${POSTGRES_URL}
    API_PORT: ${API_PORT}
    DISABLE_SECURITY: ${DISABLE_SECURITY}
    UNIQUE_WS_ENDPOINT: ${UNIQUE_WS_ENDPOINT}
    KUSAMA_WS_ENDPOINT: ${KUSAMA_WS_ENDPOINT}
    UNIQUE_NETWORK: ${UNIQUE_NETWORK}
    KUSAMA_NETWORK: ${KUSAMA_NETWORK}
    COMMISSION_PERCENT: ${COMMISSION_PERCENT}
    UNIQUE_START_FROM_BLOCK: ${UNIQUE_START_FROM_BLOCK}
    KUSAMA_START_FROM_BLOCK: ${KUSAMA_START_FROM_BLOCK}
    AUTO_DB_MIGRATIONS: ${AUTO_DB_MIGRATIONS}
    SENTRY_ENABLED: ${SENTRY_ENABLED}
#    SENTRY_ENV: ${SENTRY_ENV}
#    SENTRY_DSN: ${SENTRY_DSN}
  depends_on:
    - postgres

services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    image: uniquenetwork/marketplace-frontend:develop
    environment:
      - UNIQUE_API_URL=/
    volumes:
      - ./static/footer.html:/usr/share/nginx/html/footer.html:ro
      - ./static/logo.svg:/usr/share/nginx/html/logos/logo.svg:ro
      - ./static/variables.css:/usr/share/nginx/html/variables.css:ro
    depends_on:
      - backend


  backend:
    container_name: backend
    <<: *marketplace-backend

  escrow-unique:
    container_name: escrow-unique
    command: [ "npm", "run", "escrow:unique" ]
    <<: *marketplace-backend

  escrow-kusama:
    container_name: escrow-kusama
    command: [ "npm", "run", "escrow:kusama" ]
    <<: *marketplace-backend

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: 'marketplace_db'
      POSTGRES_USER: 'marketplace'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_PORT: '5432'
      POSTGRES_INITDB_ARGS: "--auth-local=trust"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro


